/**
 * Created by lenovo on 2017/7/20.
 */
import {Timu}from './timu'

export const  tis:Timu[]=[
  {id: "1", tigan: " <p><img src='http://tiku.21cnjy.com/tikupic/ce/44/cee440555b16b4721bac052b1a00c754.png' style='vertical-align:middle;' />&nbsp;二项展开式中的常数项为 （&nbsp;）<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='25%'>A．56<b  alt='免费中小学题库'  class='hidejammersa' ></b>&nbsp;</td><td width='25%'>B．112<span  alt='21题库'  class='hidejammersa' ></span>&nbsp;</td><td width='25%'>C．-56<i  alt='21题库'  class='hidejammersa' ></i>&nbsp;</td><td width='25%'>D．-112<font  title='中小学题库'  class='hidejammersa' ></font>&nbsp;</td></tr></table></p>", answer:"A",
    explain: "<p>∵<img src='http://tiku.21cnjy.com/tikupic/12/76/12b76ff11b283a5db0a8fbc071fe21c1.png' style='vertical-align:middle;' />&nbsp;，则<img src='http://tiku.21cnjy.com/tikupic/3b/3d/3b73d78fdfb45bbbbdaf78a33f6bc31a.png' style='vertical-align:middle;' />&nbsp;，解得r=2，<br />∴常数项为<img src='http://tiku.21cnjy.com/tikupic/e3/31/e36313df0b1d8d11261a05891204ed15.png' style='vertical-align:middle;' />&nbsp;,故选A<br />考点：本题考查二项式定理展开式的通项公式<br />点评：解决本题的关键是掌握项式定理展开式的通项公式,注意符号</i></p>", zhishidian: "统计与概率", zcuoyin:"符号出错"
  },
  {id: "2", tigan:" <p>在空间直角坐标系中，点<img src='http://tiku.21cnjy.com/tikupic/ac/99/aca99026a22cc3d56ad8cebd0b40e148.png' style='vertical-align:middle;' />，过点P作平面xOy的垂线PQ，则Q的坐标为（&nbsp;）<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='25%'>A．<img src='http://tiku.21cnjy.com/tikupic/4a/a3/4a1a37fb804c0beb0006c5446a7eb961.png' style='vertical-align:middle;' /><u class='jammerd42'  alt='21题库'></u> </td><td width='25%'>B．<img src='http://tiku.21cnjy.com/tikupic/9c/85/9cb859fbd0d968a2c48493c7fff7b8a8.png' style='vertical-align:middle;' /><u class='jammerd42'  alt='免费中小学题库'>&nbsp; B</u> </td><td width='25%'>C．<img src='http://tiku.21cnjy.com/tikupic/cb/a4/cbda484b6d7da1df49d7401db13ec9cf.png' style='vertical-align:middle;' /><b class='jammerd42'  title='中小学题库'></b> </td><td width='25%'>D．<img src='http://tiku.21cnjy.com/tikupic/a5/71/a5b71c1f478603ac7c5caa55db4fd261.png' style='vertical-align:middle;' /><code class='jammerd42'  title='tiku.21cnjy.com'></code> </td></tr></table></p>",
    answer:"D",explain:"<p>过点P作平面xOy的垂线PQ，则P，Q两个点的横标和纵标相同，只有竖标不同，在xoy平面上的点的竖标为0，写出要求点的坐标．<br />解：空间直角坐标系中，点<img src='http://tiku.21cnjy.com/tikupic/02/da/02cda42ba1b38975f67c4219b13ea160.png' style='vertical-align:middle;' />，<br />过点P作平面xOy的垂线PQ，<br />则P，Q两个点的横标和纵标相同，只有竖标不同，<br />在xoy平面上的点的竖标为0，<br />∴Q（1，<img src='http://tiku.21cnjy.com/tikupic/be/db/be3db6eec3fe72f90b13b948bbc64358.png' style='vertical-align:middle;' />，0）<br />故选D．<br />点评：不同考查空间中点的坐标，是一个基础题，这种题目一般不会单独出现，它只是立体几何与空间向量中所出现的题目的一个小部分．</i></p>", zhishidian: "立体几何", zcuoyin:"逻辑出错"
  },
{id: "3", tigan:"<p>某珠宝店丢了一件珍贵珠宝，以下四人中只有一人说真话，只有一人偷了珠宝．甲：我没有偷；乙：丙是小偷；丙：丁是小偷；丁：我没有偷．根据以上条件，可以判断偷珠宝的人是<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='25%'>A．甲<u class='this_jammer'  alt='21题库'></u> </td><td width='25%'>B．乙<font class='this_jammer'  alt='免费中小学题库'></font> </td><td width='25%'>C．丙<code class='this_jammer'  title='tiku.21cnjy.com'></code> </td><td width='25%'>D．丁<address class='this_jammer'  title='tiku.21cnjy.com'></address> </td></tr></table></p>",
  answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "逻辑用语", zcuoyin:"逻辑出错"
},
  {id: "4", tigan:"<p>从2 004名学生中抽取50名组成参观团，若采用下面的方法选取，先用简单随机抽样从2 004人中剔除4人，剩下的2 000人再按系统抽样的方法进行，则每人入选的概率是（&nbsp;）<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='100%'>A．不全相等<i class='hidejammersa'  alt='免费中小学题库'></i></td></tr><tr><td width='100%'>B．均不相等<address class='hidejammersa'  title='中小学题库'></address></td></tr><tr><td width='100%'>C．都相等，且为<img src='http://tiku.21cnjy.com/tikupic/36/e0/36be068c3512feb26a0b7c4c04ae83c6.png' style='vertical-align:middle;' /><b class='hidejammersa'  title='中小学题库'></b></td></tr><tr><td width='100%'>D．都相等，且为<img src='http://tiku.21cnjy.com/tikupic/5b/9b/5b69b3c393a0a4124a2e1046d17731ff.png' style='vertical-align:middle;' /><span class='hidejammersa'  title='tiku.21cnjy.com'></span></td></tr></table></p>",
    answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "数据统计", zcuoyin:"逻辑出错"
  },
  {id: "5", tigan:"<p>如图，大正方形靶盘的边长为<img src='http://tiku.21cnjy.com/tikupic/56/8c/5688c5b6b42351e4f90ae8e600781cdb.png' style='vertical-align:middle;' />，四个全等的直角三角形围成一个小正方形，即阴影区域．较短的直角边长为2，现向大正方形靶盘投掷飞镖，则飞镖落在阴影区域的概率为（&nbsp;&nbsp;&nbsp;&nbsp;）<br /><img src='http://tiku.21cnjy.com/tikupic/b2/49/b2b499cc582f260713fa8c75a4512f24.jpg' style='vertical-align:middle;' /><table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='25%'>A．<img src='http://tiku.21cnjy.com/tikupic/62/54/62654cc2d200eb0d550bf9aef68204e5.png' style='vertical-align:middle;' /><font class='hidejammersa'  title='中小学题库'></font></td><td width='25%'>B．<img src='http://tiku.21cnjy.com/tikupic/ab/42/ab642500fa60eadcbb4ad4ee9c820b20.png' style='vertical-align:middle;' /><code class='hidejammersa'  title='中小学题库'></code></td><td width='25%'>C．<img src='http://tiku.21cnjy.com/tikupic/9c/2e/9c92e8d7fb1af2d58d8d97e8c92f2c12.png' style='vertical-align:middle;' /><i class='hidejammersa'  alt='免费中小学题库'></i></td><td width='25%'>D．<img src='http://tiku.21cnjy.com/tikupic/98/df/986df3cd6f0973f8099e8f0cc36d2383.png' style='vertical-align:middle;' /><address class='hidejammersa'  title='tiku.21cnjy.com'></address></td></tr></table></p>",
    answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "阴影面积", zcuoyin:"逻辑出错"
  },
  {id: "6", tigan:"<p>已知<img src='http://tiku.21cnjy.com/tikupic/64/e3/643e3cd0b3d8fe820adc7e593f2c47c4.png' style='vertical-align:middle;' />，则“<img src='http://tiku.21cnjy.com/tikupic/aa/74/aa57488020e979d13c01db076bbe152a.png' style='vertical-align:middle;' />”是“<img src='http://tiku.21cnjy.com/tikupic/9c/cf/9c0cf44fa3a547d52c15841d3b4afad2.png' style='vertical-align:middle;' />”的<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='100%'>A．充分而不必要条件<code class='hidejammersa'  alt='免费中小学题库'></code></td></tr><tr><td width='100%'>B．必要而不充分条件<b class='hidejammersa'  alt='免费中小学题库'></b></td></tr><tr><td width='100%'>C．充要条件<i class='hidejammersa'  alt='免费中小学题库'></i></td></tr><tr><td width='100%'>D．既不充分也不必要条件<code class='hidejammersa'  title='中小学题库'></code></td></tr></table></p>",
    answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "条件判断", zcuoyin:"逻辑出错"
  },
  {id: "7", tigan:"<p> <p>如果命题<img src='http://tiku.21cnjy.com/tikupic/4b/5a/4b65a2b0df94f49650a36b718bef7e7e.png' style='vertical-align:middle;' />为真命题，<img src='http://tiku.21cnjy.com/tikupic/58/36/58a365e830e3806e9fa4b664a86bb76c.png' style='vertical-align:middle;' />为假命题，那么（&nbsp;&nbsp;）<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='100%'>A．命题p、q都是真命题<address  alt='免费中小学题库' class='this_jammer'></address> </td></tr><tr><td width='100%'>B．命题p、q都是假命题 <code  alt='免费中小学题库' class='this_jammer'></code> </td></tr><tr><td width='100%'>C．命题p、q至少有一个是真命题<b  alt='免费中小学题库' class='this_jammer'></b> </td></tr><tr><td width='100%'>D．命题p、q只有一个真命题<b  title='中小学题库' class='this_jammer'></b> </td></tr></table></p>",
    answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "命题逻辑", zcuoyin:"逻辑出错"
  },
  {id: "8", tigan:" <p>“<img src='http://tiku.21cnjy.com/tikupic/63/5c/63d5cae2856584f8682451560400f28c.png' style='vertical-align:middle;' />”是“<img src='http://tiku.21cnjy.com/tikupic/9b/ad/9beaddcb3d78bcd1e289fc8dc8335499.png' style='vertical-align:middle;' />”的（&nbsp;&nbsp;&nbsp;）<table name='optionsTable' cellpadding='0' cellspacing='0' width='100%'><tr><td width='50%'>A．充分不必要条件<u class='hidejammersa'  alt='免费中小学题库'></u></td><td width='50%'>B．必要不充分条件<font class='hidejammersa'  title='中小学题库'></font></td></tr><tr><td width='50%'>C．充分必要条件<font class='hidejammersa'  title='tiku.21cnjy.com'></font></td><td width='50%'>D．既不充分也不必要条件<address class='hidejammersa'  title='中小学题库'></address></td></tr></table></p>",
    answer:"B",explain:"<div class=&quot;que-stem&quot;> <div class=&quot;questem-inner bdjson&quot;><p><span>已知抛物线C:y</span><span class=&quot;ext_valign_sup&quot;>2</span><span>=4x的焦点为F,过点K(-1,0)的直线l与C相交为A、B两点，点A关于x轴的对称点为D.</span></p><p  >（1）证明：点F在直线BD上；</p><p><span>（2）设</span><img src=assets/img/ti-math.jpg width=&quot;105px&quot; height=&quot;43px&quot; class=&quot;scale-img&quot;><span>，求△BDK的内切圆M的方程.</span></p></div></div>", zhishidian: "内切圆", zcuoyin:"逻辑出错"
  }
];
